{% set name = "ambit" %}
{% set version = "0.7" %}
{% set sha256 = "97a4360db5cad6c9d2bc0932fc8641a3feb34a809c192c99886880073e87f8c2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://github.com/jturney/{{ name }}/archive/v{{ version }}.tar.gz
    patches:
      -  0001-lapack-private-to-avoid-overlinking.patch
    sha256: {{ sha256 }}
  - url: https://github.com/psi4/iomp5md/archive/31b4ccb.tar.gz               # [win]
    sha256: d9c6ad3976183f54b676335885d8557d67ca7b25ac4115b91b4cc42281d95f7c  # [win]
    folder: external_src                                                      # [win]

build:
  number: 1
  binary_relocation: true

outputs:
  - name: ambit
    script: build-cxx.sh                                                       # [unix]
    script: bld-cxx.bat                                                        # [win]
    build:
      skip: true                                                               # [win]
      run_exports:
        - {{ pin_subpackage('ambit', max_pin='x.x') }}
      ignore_run_exports:
        # not using hdf5's fortran interface
        - libgfortran-ng
        - libgfortran5
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - llvm-openmp                                                          # [osx]
        - libgomp                                                              # [linux]
      host:
        - hdf5
        - libblas
        - liblapack
        - intel-openmp                                                         # [win]
      run:
        - intel-openmp                                                         # [win]
    test:
      requires:
        - m2w64-binutils                                                       # [win]   # provides objdump.exe
      commands:
        # Verify library
        - test -f $PREFIX/lib/libambit$SHLIB_EXT                               # [unix]
        - test ! -f $PREFIX/lib/libambit.a                                     # [unix]
        - if not exist %PREFIX%\\Library\\lib\\ambit.lib exit 1                # [win]   # ms static lib
        - if exist %PREFIX%\\Library\\bin\\ambit.dll exit 1                    # [win]   # ms dyn lib absent
        # Verify accessories
        - test -f $PREFIX/include/ambit/tensor.h                               # [unix]
        - test -f $PREFIX/share/cmake/ambit/ambitConfig.cmake                  # [unix]
        - test -f $PREFIX/share/cmake/ambit/ambitTargets-shared.cmake          # [unix]
        - if not exist %PREFIX%\\Library\\include\\ambit\\tensor.h exit 1      # [win]
        - if not exist %PREFIX%\\Library\\share\\cmake\\ambit\\ambitConfig.cmake exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\cmake\\ambit\\ambitTargets-static.cmake exit 1  # [win]
        # Inspect linkage
        - ldd -v $PREFIX/lib/libambit$SHLIB_EXT                                # [linux]
        - otool -L $PREFIX/lib/libambit$SHLIB_EXT                              # [osx]
        - objdump.exe -p %PREFIX%\\Library\\lib\\ambit.lib | findstr /i "dll"  # [win]

  - name: pyambit
    script: build-py.sh                                                        # [unix]
    script: bld-py.bat                                                         # [win]
    build:
      skip: true                                                               # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - python                                                               # [build_platform != target_platform]
        - cross-python_{{ target_platform }}                                   # [build_platform != target_platform]
        - numpy                                                                # [build_platform != target_platform]
        - pybind11                                                             # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('ambit', exact=True) }}
        - python
        - pybind11
        - pybind11-abi
        - numpy
        - libblas                                                              # [win]
        - liblapack                                                            # [win]
        - intel-openmp                                                         # [win]
      run:
        - {{ pin_subpackage('ambit', exact=True) }}
        - python
        - intel-openmp                                                         # [win]
    test:
      requires:
        - pip                                                                            # provides `pip check`
        - pytest
        - numpy
        - m2w64-binutils                                                       # [win]   # provides objdump.exe
      files:
        - test_ambit.py
      imports:
        - ambit
      commands:
        - ls -l $SP_DIR/ambit                                                  # [unix]
        - dir %SP_DIR%\\ambit                                                  # [win]
        # Verify module
        - test -f $SP_DIR/ambit/pyambit*.so                                    # [unix]
        - if not exist %SP_DIR%\\ambit\\pyambit*.pyd exit 1                    # [win]
        # Verify accessories
        - test -f $PREFIX/share/cmake/ambit/ambitConfig.cmake                  # [unix]
        - test -f $PREFIX/share/cmake/ambit/ambitTargets-Python.cmake          # [unix]
        - if not exist %PREFIX%\\Library\\share\\cmake\\ambit\\ambitConfig.cmake exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\cmake\\ambit\\ambitTargets-Python.cmake exit 1  # [win]
        # Inspect linkage
        - ldd -v $SP_DIR/ambit/pyambit*.so                                     # [linux]
        - otool -L $SP_DIR/ambit/pyambit*.so                                   # [osx]
        - objdump.exe -p %SP_DIR%\\ambit\\pyambit.*.pyd | findstr /i "dll"     # [win]
        # Actually test
        - pip check
        - python test_ambit.py
        - pytest -v -rws --color yes $SP_DIR/ambit                             # [unix]
        - pytest -v -rws --color yes %SP_DIR%\\ambit                           # [win]

about:
  home: https://github.com/jturney/ambit
  dev_url: https://github.com/jturney/ambit
  license: LGPL-3.0-only
  license_url: https://opensource.org/license/lgpl-3-0/
  license_file:
    - COPYING
    - COPYING.LESSER
  license_family: LGPL
  summary: "J. Turney's C++ library for the implementation of tensor product calculations"

extra:
  feedstock-name: ambit
  recipe-maintainers:
    - loriab
    - jturney

# NOTES
# * ambit on windows works, but skipping until get the import lib for intel-openmp issue sorted out
#   (see staged-recipes discussion and psi4 feedstock recipe)
# * pyambit on windows builds but doesn't work (see snippet in bld.bat here)
